# Generated by Django 5.2.6 on 2025-10-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaservicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoriaservicio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
