# Generated by Django 5.2.6 on 2025-10-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_categoriaservicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
