# Generated by Django 5.2.6 on 2025-10-21 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_permiso_rol_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='canal',
            field=models.CharField(choices=[('WEB', 'Web'), ('PRESENCIAL', 'Presencial')], default='PRESENCIAL', max_length=15),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='monto_seña',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='turno',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='turno',
            name='reembolsado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='tipo_pago',
            field=models.CharField(choices=[('SENA_50', 'Seña 50%'), ('TOTAL', 'Pago Total'), ('PENDIENTE', 'Pendiente de Pago')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20),
        ),
    ]
