# Generated by Django 5.2.6 on 2025-10-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_turno_canal_turno_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=15),
        ),
    ]
