# Generated by Django 5.2.6 on 2025-10-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_rename_stock_producto_stock_actual_producto_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='usuarios.proveedor'),
        ),
    ]
