# Generated by Django 5.2.6 on 2025-10-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_producto_proveedor_producto_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
