# Generated by Django 5.2.6 on 2025-11-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_metodopago_alter_venta_medio_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AddField(
            model_name='metodopago',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión', max_digits=5),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='requiere_confirmacion',
            field=models.BooleanField(default=False, help_text='Si requiere confirmación manual (ej: transferencia)'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('MERCADO_PAGO', 'Mercado Pago')], default='EFECTIVO', max_length=20),
        ),
    ]
