# Generated by Django 5.2.6 on 2025-11-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_metodopago_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={},
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='comision_porcentaje',
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='requiere_confirmacion',
            field=models.BooleanField(default=False),
        ),
    ]
