# Generated by Django 5.2.6 on 2025-11-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_metodopago_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia/QR')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table=None,
        ),
    ]
