# Generated by Django 5.2.6 on 2025-11-04 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_pedido_detallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
