# Generated by Django 5.2.6 on 2025-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_propuesto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio ofrecido por el proveedor', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio acordado final', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('EN_COTIZACION', 'En cotización'), ('CONFIRMADO', 'Confirmado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='EN_COTIZACION', max_length=20),
        ),
    ]
