# Generated by Django 5.2.6 on 2025-11-11 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_detallepedido_precio_propuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecioProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del proveedor', max_digits=10)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje de ganancia (ej: 30 para +30%)', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios_proveedores', to='usuarios.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='usuarios.proveedor')),
            ],
            options={
                'verbose_name': 'Lista de precios de proveedor',
                'verbose_name_plural': 'Listas de precios de proveedores',
                'db_table': 'lista_precios_proveedores',
                'unique_together': {('proveedor', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margen_anterior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margen_nuevo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='usuarios.listaprecioproveedor')),
            ],
            options={
                'verbose_name': 'Historial de precios',
                'verbose_name_plural': 'Historial de precios',
                'db_table': 'historial_precios',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
