# Generated by Django 5.2.6 on 2025-11-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_listaprecioproveedor_historialprecios'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together=set(),
        ),
    ]
