# Generated by Django 5.2.6 on 2025-11-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_alter_detallepedido_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listaprecioproveedor',
            unique_together=set(),
        ),
    ]
