# Generated by Django 5.2.6 on 2025-11-14 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresTurnoLiberado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deseada', models.DateField()),
                ('hora_deseada', models.TimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notificado', models.BooleanField(default=False)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses_turnos', to=settings.AUTH_USER_MODEL)),
                ('peluquero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses_peluquero', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.servicio')),
            ],
            options={
                'db_table': 'intereses_turnos_liberados',
                'ordering': ['fecha_registro'],
                'unique_together': {('cliente', 'servicio', 'peluquero', 'fecha_deseada', 'hora_deseada')},
            },
        ),
    ]
