# Generated by Django 5.2.6 on 2025-11-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_interesturnoliberado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReoferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_por_defecto', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('tiempo_limite_respuesta', models.IntegerField(default=60)),
                ('max_intentos_notificacion', models.IntegerField(default=3)),
                ('activo', models.BooleanField(default=True)),
                ('notificar_email', models.BooleanField(default=True)),
                ('notificar_whatsapp', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Reoferta',
                'verbose_name_plural': 'Configuraciones de Reoferta',
                'db_table': 'configuracion_reoferta',
            },
        ),
        migrations.AlterModelOptions(
            name='interesturnoliberado',
            options={'ordering': ['fecha_registro', 'prioridad']},
        ),
        migrations.AddField(
            model_name='interesturnoliberado',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='interesturnoliberado',
            name='fecha_oferta_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interesturnoliberado',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interesturnoliberado',
            name='oferta_aceptada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interesturnoliberado',
            name='oferta_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interesturnoliberado',
            name='orden_notificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interesturnoliberado',
            name='tiempo_limite_respuesta',
            field=models.IntegerField(default=60),
        ),
    ]
