# Generated by Django 5.2.6 on 2025-11-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_marca_alter_producto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='productos_especificos',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='productos_que_ofrece',
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='productos', to='usuarios.proveedor'),
        ),
    ]
