# Generated by Django 5.2.6 on 2025-11-22 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_producto_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interesturnoliberado',
            old_name='fecha_notificacion',
            new_name='fecha_envio_oferta',
        ),
        migrations.RemoveField(
            model_name='interesturnoliberado',
            name='fecha_oferta_enviada',
        ),
        migrations.RemoveField(
            model_name='interesturnoliberado',
            name='notificado',
        ),
        migrations.RemoveField(
            model_name='interesturnoliberado',
            name='oferta_aceptada',
        ),
        migrations.RemoveField(
            model_name='interesturnoliberado',
            name='oferta_enviada',
        ),
        migrations.AddField(
            model_name='interesturnoliberado',
            name='estado_oferta',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Oferta Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='interesturnoliberado',
            name='ip_aceptacion',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interesturnoliberado',
            name='token_oferta',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='cliente_asignado_reoferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_asignados_reoferta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_expiracion_oferta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='oferta_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='token_reoferta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('DISPONIBLE', 'Disponible')], default='RESERVADO', max_length=20),
        ),
    ]
