# Generated by Django 5.2.6 on 2025-11-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_rename_fecha_notificacion_interesturnoliberado_fecha_envio_oferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesturnoliberado',
            name='turno_liberado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intereses_asociados', to='usuarios.turno'),
        ),
    ]
