# Generated by Django 5.2.6 on 2025-11-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_interesturnoliberado_turno_liberado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interesturnoliberado',
            unique_together={('cliente', 'peluquero', 'fecha_deseada', 'hora_deseada')},
        ),
        migrations.AlterField(
            model_name='interesturnoliberado',
            name='turno_liberado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intereses_asociados', to='usuarios.turno'),
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table='metodos_pago',
        ),
    ]
