# Generated by Django 5.2.6 on 2025-11-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_alter_interesturnoliberado_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
