# Generated by Django 5.2.6 on 2025-11-29 08:14

import django.db.models.deletion
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0039_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='SolicitudPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Esperando Respuestas'), ('CERRADA', 'Cerrada / Decisión Tomada')], default='PENDIENTE', max_length=20)),
                ('pedido_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_presupuesto', to='usuarios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=100, unique=True)),
                ('precio_ofrecido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_entrega', models.IntegerField(blank=True, help_text='Días hábiles', null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_email_enviado', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respondio', models.BooleanField(default=False)),
                ('es_la_mejor', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='usuarios.solicitudpresupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReabastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(default=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Esperando Respuestas'), ('CERRADA', 'Cerrada / Decisión Tomada')], default='PENDIENTE', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_acceso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('precio_ofrecido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_entrega', models.PositiveIntegerField(blank=True, help_text='Días hábiles para entregar', null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('respondió', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='usuarios.solicitudreabastecimiento')),
            ],
        ),
    ]
