# Generated by Django 5.2.6 on 2025-12-01 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_producto_stock_minimo_solicitudpresupuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PromocionReactivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único para canjear', max_length=20, unique=True)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa (Enviada)'), ('USADA', 'Usada (Canjeada)'), ('VENCIDA', 'Vencida (No aprovechada)')], default='ACTIVA', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones_reactivacion', to=settings.AUTH_USER_MODEL)),
                ('turno_canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_usada', to='usuarios.turno')),
            ],
        ),
    ]
