# Generated by Django 5.2.6 on 2025-12-02 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0041_alter_pedido_estado_promocionreactivacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={},
        ),
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='marca',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='marca',
            table=None,
        ),
    ]
