# Generated by Django 5.2.6 on 2025-12-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0042_alter_marca_options_marca_descripcion_marca_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='marcas', to='usuarios.proveedor'),
        ),
    ]
