# Generated by Django 5.2.6 on 2025-12-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0043_marca_proveedores'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('nombre', 'marca'), name='unique_producto_nombre_marca'),
        ),
    ]
