# Generated by Django 5.2.6 on 2025-12-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0046_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='navegador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
