# Generated by Django 5.2.6 on 2025-12-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0047_auditoria_navegador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de Auditoría'},
        ),
        migrations.RenameField(
            model_name='auditoria',
            old_name='ip',
            new_name='ip_address',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='navegador',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='modelo_afectado',
            field=models.CharField(default='SISTEMA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='detalles',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='objeto_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='auditoria',
            table=None,
        ),
    ]
