# Generated by Django 5.2.6 on 2025-12-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0048_alter_auditoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='unique_producto_nombre_marca',
        ),
        migrations.AddField(
            model_name='producto',
            name='lote_reposicion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('nombre', 'marca'), name='unique_producto_nombre_marca'),
        ),
    ]
