# Generated by Django 5.2.6 on 2025-12-20 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0050_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado a Proveedor'), ('CONFIRMADO', 'Confirmado por Proveedor'), ('ENTREGADO', 'Recibido en Local'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
