# Generated by Django 5.2.6 on 2025-12-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0051_pedido_token_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cantidad_ofertada',
            field=models.IntegerField(blank=True, help_text='Cantidad real que tiene el proveedor', null=True),
        ),
    ]
