# Generated by Django 5.2.6 on 2025-12-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0054_servicio_activo_servicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje que gana el peluquero por este servicio (0 a 100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='turno',
            name='monto_comision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sueldo_fijo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Usar solo para empleados con fijo (ej. Recepción)', max_digits=10, verbose_name='Sueldo Fijo Mensual'),
        ),
    ]
