# Generated by Django 5.2.6 on 2025-12-28 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0055_servicio_porcentaje_comision_turno_monto_comision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('monto_comisiones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_sueldo_fijo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to=settings.AUTH_USER_MODEL)),
                ('turnos_pagados', models.ManyToManyField(blank=True, to='usuarios.turno')),
            ],
            options={
                'db_table': 'liquidaciones',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
