# Generated by Django 5.2.6 on 2025-12-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0056_liquidacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20),
        ),
    ]
