# Generated by Django 5.2.6 on 2025-12-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0057_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='duracion_total',
            field=models.IntegerField(default=0, help_text='Duración total en minutos'),
        ),
    ]
