# Generated by Django 5.2.6 on 2026-01-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0058_turno_duracion_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago (Web) '), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20),
        ),
    ]
