# Generated by Django 5.2.6 on 2026-01-05 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0059_alter_turno_medio_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Esperando Pago'), ('PAGADO', 'Pagado - A preparar'), ('EN_PREPARACION', 'En preparación'), ('LISTO_RETIRO', 'Listo para retirar en Local'), ('EN_CAMINO', 'En camino (Moto/Correo)'), ('ENTREGADO', 'Entregado / Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_PAGO', max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('RETIRO', 'Retiro en el Local'), ('MOTO', 'Envío Moto (San Vicente)'), ('CORREO', 'Envío Correo (Nacional)')], default='RETIRO', max_length=20)),
                ('direccion_envio', models.TextField(blank=True, help_text='Dirección completa si es envío', null=True)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mp_payment_id', models.CharField(blank=True, help_text='ID de pago de MercadoPago', max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total productos + envío', max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_web', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='usuarios.pedidoweb')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido Web',
                'verbose_name_plural': 'Detalles de Pedidos Web',
            },
        ),
    ]
