# Generated by Django 5.2.6 on 2026-01-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0060_pedidoweb_detallepedidoweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default='Los Últimos Serán Los Primeros', max_length=255)),
                ('cuil_cuit', models.CharField(default='00-00000000-0', max_length=20)),
                ('inicio_actividad', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(default='Calle Falsa 123', max_length=255)),
                ('telefono', models.CharField(default='(3755) 12-3456', max_length=50)),
                ('email', models.EmailField(default='contacto@hairsoft.com', max_length=254)),
                ('margen_horas_cancelacion', models.PositiveIntegerField(default=24, help_text='Horas antes para no perder la seña')),
                ('politica_senia', models.TextField(default='Si cancela antes de las horas establecidas, se pierde la seña.')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
