# Generated by Django 5.2.6 on 2026-01-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0061_configuracionsistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'verbose_name': 'Configuración del Sistema'},
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='cuil_cuit',
            field=models.CharField(default='20-12345678-9', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='direccion',
            field=models.CharField(default='Avenida Libertador 600, San Vicente - Misiones', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='margen_horas_cancelacion',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='politica_senia',
            field=models.TextField(default='Política de señas: ...'),
        ),
    ]
