# Generated by Django 5.2.6 on 2026-01-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0062_alter_configuracionsistema_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='cuil_cuit',
            field=models.CharField(default='27-23456789-3', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='telefono',
            field=models.CharField(default='3755-72716', max_length=50),
        ),
    ]
