# Generated by Django 5.2.6 on 2026-02-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0063_alter_configuracionsistema_cuil_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoweb',
            name='datos_entrega_interna',
            field=models.CharField(blank=True, help_text='Nombre del repartidor o nro de guía', max_length=255, null=True),
        ),
    ]
