# Generated by Django 5.2.6 on 2026-02-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0064_pedidoweb_datos_entrega_interna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoweb',
            name='datos_entrega_interna',
            field=models.CharField(blank=True, help_text='Nombre del cadete', max_length=255, null=True),
        ),
    ]
