# Generated by Django 5.2.6 on 2026-02-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0065_alter_pedidoweb_datos_entrega_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='mp_refund_id',
            field=models.CharField(blank=True, help_text='ID de comprobante de devolución', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='nro_transaccion',
            field=models.CharField(blank=True, help_text='Para transferencias manuales', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='obs_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='margen_horas_cancelacion',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='politica_senia',
            field=models.TextField(default='Política de señas: Reembolso total si cancelas con tiempo.'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Transferencia / Pago Digital (Web)'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20),
        ),
    ]
