# Generated by Django 5.2.6 on 2026-02-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0066_turno_motivo_cancelacion_turno_mp_refund_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Transferencia / Pago Digital (Web)'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta (Posnet Local)'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nro_transaccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
