# Generated by Django 5.2.6 on 2026-02-02 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0067_alter_turno_medio_pago_alter_turno_nro_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
