# Generated by Django 5.2.6 on 2026-02-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0068_alter_turno_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='reembolso_estado',
            field=models.CharField(choices=[('NO_APLICA', 'No Aplica'), ('PENDIENTE', 'Pendiente de Devolución'), ('COMPLETADO', 'Devuelto al Cliente')], default='NO_APLICA', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('DISPONIBLE', 'Disponible')], default='RESERVADO', max_length=20),
        ),
    ]
