# Generated by Django 5.2.6 on 2026-02-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0069_turno_reembolso_estado_alter_turno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='duracion_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turno',
            name='mp_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
