# Generated by Django 5.2.6 on 2026-02-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0070_alter_turno_duracion_total_alter_turno_mp_refund_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20),
        ),
    ]
