# Generated by Django 5.2.6 on 2026-02-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0071_alter_turno_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='codigo_transaccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cód. Comprobante Manual'),
        ),
        migrations.AddField(
            model_name='turno',
            name='entidad_pago',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Billetera/Banco Origen'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADOPAGO', 'Mercado Pago')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago'), ('TRANSFERENCIA', 'Transferencia'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20),
        ),
    ]
