# Generated by Django 5.2.6 on 2026-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0072_turno_codigo_transaccion_turno_entidad_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='codigo_transaccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Comprobante Manual'),
        ),
        migrations.AddField(
            model_name='venta',
            name='entidad_pago',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Billetera/Banco Origen'),
        ),
        migrations.AddField(
            model_name='venta',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='nro_transaccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
