# Generated by Django 5.2.6 on 2026-02-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0073_venta_codigo_transaccion_venta_entidad_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Descuento aplicado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='monto_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto sin descuento'),
        ),
    ]
