# Generated by Django 5.2.6 on 2026-02-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0074_turno_descuento_aplicado_turno_monto_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocionreactivacion',
            name='canal_envio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Canal de envío'),
        ),
        migrations.AddField(
            model_name='promocionreactivacion',
            name='mensaje_sid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de mensaje Twilio'),
        ),
        migrations.AddField(
            model_name='promocionreactivacion',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de transacción/pago'),
        ),
    ]
