# Generated by Django 5.2.6 on 2026-02-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0075_promocionreactivacion_canal_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='dias_inactividad_clientes',
            field=models.PositiveIntegerField(default=60, help_text='Días sin venir para considerar al cliente inactivo y enviarle promo.'),
        ),
    ]
