# Generated by Django 5.2.6 on 2026-02-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0076_configuracionsistema_dias_inactividad_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='config/'),
        ),
    ]
