# Generated by Django 5.2.6 on 2026-02-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0077_configuracionsistema_logo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interesturnoliberado',
            unique_together={('cliente', 'peluquero', 'fecha_deseada', 'hora_deseada', 'servicio')},
        ),
    ]
