# Generated by Django 5.2.6 on 2026-02-16 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0078_alter_interesturnoliberado_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Silla 1, Puesto Ventana, Lavacabezas', max_length=50)),
                ('activa', models.BooleanField(default=True, help_text='Desmarcar si la silla está rota o fuera de servicio')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Número para ordenar visualmente (1, 2, 3...)')),
            ],
            options={
                'verbose_name': 'Silla / Puesto',
                'verbose_name_plural': 'Sillas / Puestos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='silla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='usuarios.silla', verbose_name='Silla Asignada'),
        ),
    ]
