# Generated by Django 5.2.6 on 2026-02-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0079_silla_turno_silla'),
    ]

    operations = [
        migrations.AddField(
            model_name='silla',
            name='motivo_inactividad',
            field=models.CharField(blank=True, help_text='Razón por la cual no se usa', max_length=100, null=True),
        ),
    ]
