# Generated by Django 5.2.6 on 2026-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0080_silla_motivo_inactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='codigo_transaccion_restante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cód. Comprobante Restante'),
        ),
        migrations.AddField(
            model_name='turno',
            name='entidad_pago_restante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Billetera/Banco Restante'),
        ),
        migrations.AddField(
            model_name='turno',
            name='medio_pago_restante',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago'), ('TRANSFERENCIA', 'Transferencia'), ('PENDIENTE', 'Pendiente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20),
        ),
    ]
