# Generated by Django 5.2.6 on 2026-02-25 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0081_turno_codigo_transaccion_restante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Motivo por el cual se anuló la venta.')),
                ('monto_devuelto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Usuario/Admin que ejecutó la anulación.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(help_text='Venta que fue anulada.', on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito', to='usuarios.venta')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'db_table': 'notas_credito',
                'ordering': ['-fecha'],
            },
        ),
    ]
