# Generated by Django 5.2.6 on 2026-02-26 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0083_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_anterior', models.IntegerField()),
                ('cantidad_nueva', models.IntegerField()),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_ajuste', models.CharField(default='AJUSTE_MANUAL', max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='usuarios.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_stock',
                'ordering': ['-fecha'],
            },
        ),
    ]
