# Generated by Django 5.2.6 on 2026-02-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0084_historialstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_anulacion',
            field=models.TextField(blank=True, help_text='Razón por la cual se canceló la venta.', null=True),
        ),
    ]
