# Generated by Django 5.2.6 on 2026-02-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0085_venta_fecha_anulacion_venta_motivo_anulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('ANULAR_VENTA', 'Anulación de Venta'), ('AJUSTE_STOCK', 'Ajuste de Stock')], max_length=20),
        ),
    ]
