# Generated by Django 5.2.6 on 2026-02-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0086_alter_auditoria_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriaservicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
