# Generated by Django 5.2.6 on 2026-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0087_categoriaproducto_activo_categoriaservicio_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silla',
            name='nombre',
            field=models.CharField(help_text='Ej: Silla 1, Puesto Ventana, Lavacabezas', max_length=50, unique=True),
        ),
    ]
