# Generated by Django 5.2.6 on 2026-03-02 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0089_alter_marca_nombre_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Caja Principal, Caja Mostrador', max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Si es False, la caja está inhabilitada')),
                ('motivo_inactividad', models.TextField(blank=True, help_text='Razón si se deshabilita la caja', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_final_efectivo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_final_mp_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_final_transf_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='usuarios.caja')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('concepto', models.CharField(choices=[('TURNO_PRESENCIAL', 'Cobro de Turno Presencial'), ('TURNO_WEB', 'Cobro de Turno Web'), ('VENTA', 'Venta de Productos'), ('PEDIDO_WEB', 'Pedido Web'), ('PAGO_PROVEEDOR', 'Pago a Proveedor'), ('LIQUIDACION_SUELDO', 'Liquidación de Sueldos'), ('GASTO_OPERATIVO', 'Gasto Operativo (Yerba, etc)'), ('RETIRO_SOCIO', 'Retiro de Socio/Dueño'), ('OTROS', 'Otros / Ajustes')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, help_text='Detalle extra del gasto o ingreso', max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido_proveedor_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.pedido')),
                ('turno_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.turno')),
                ('venta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.venta')),
                ('sesion_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.sesioncaja')),
            ],
        ),
    ]
