# Generated by Django 5.2.6 on 2026-03-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0090_caja_sesioncaja_movimientocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncaja',
            name='saldo_inicial_mp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
