# Generated by Django 5.2.6 on 2026-03-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0091_sesioncaja_saldo_inicial_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='concepto',
            field=models.CharField(choices=[('TURNO_PRESENCIAL', 'Cobro de Turno Presencial'), ('TURNO_WEB', 'Cobro de Turno Web'), ('VENTA', 'Venta de Productos'), ('PEDIDO_WEB', 'Pedido Web'), ('PAGO_PROVEEDOR', 'Pago a Proveedor'), ('LIQUIDACION_SUELDO', 'Liquidación de Sueldos'), ('GASTO_OPERATIVO', 'Gasto Operativo (Yerba, etc)'), ('RETIRO_SOCIO', 'Retiro de Socio/Dueño'), ('FONDO_CAJA', 'Fondo de Caja (Sencillo)'), ('APORTE_SOCIO', 'Aporte de Socio/Dueño'), ('COBRO_DEUDA', 'Cobro de Deuda'), ('AJUSTE_SOBRANTE', 'Ajuste por Sobrante de Caja'), ('OTROS', 'Otros / Ajustes')], max_length=30),
        ),
    ]
