# Generated by Django 5.2.6 on 2026-03-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0093_alter_movimientocaja_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_envio_moto', models.DecimalField(decimal_places=2, default=1500.0, help_text='Precio fijo para moto mandado', max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración Web',
                'verbose_name_plural': 'Configuraciones Web',
            },
        ),
    ]
