# Generated by Django 5.2.6 on 2026-03-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0094_configuracionweb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionWeb',
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='costo_envio_moto',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10),
        ),
    ]
