# Generated by Django 5.2.6 on 2026-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0095_delete_configuracionweb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='porcentaje_descuento_promo',
            field=models.PositiveIntegerField(default=15, help_text='Porcentaje de descuento para enviar a clientes inactivos o en espera'),
        ),
    ]
