# Generated by Django 5.2.6 on 2026-03-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0096_configuracionsistema_porcentaje_descuento_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='porcentaje_descuento_reoferta',
            field=models.PositiveIntegerField(default=15, help_text='Descuento para turnos liberados (Lista de espera)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='porcentaje_descuento_promo',
            field=models.PositiveIntegerField(default=15, help_text='Porcentaje de descuento para enviar a clientes inactivos'),
        ),
    ]
