# Generated by Django 5.2.6 on 2026-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0097_configuracionsistema_porcentaje_descuento_reoferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoweb',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='obs_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
