# Generated by Django 5.2.6 on 2026-03-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0098_pedidoweb_motivo_cancelacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('ANULAR_VENTA', 'Anulación de Venta'), ('AJUSTE_STOCK', 'Ajuste de Stock'), ('APERTURA_CAJA', 'Apertura de Caja'), ('CIERRE_CAJA', 'Cierre de Caja'), ('INGRESO_MANUAL', 'Ingreso a Caja'), ('EGRESO_MANUAL', 'Egreso de Caja')], max_length=20),
        ),
    ]
