# Generated by Django 5.2.6 on 2026-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0099_alter_auditoria_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silla',
            name='orden',
            field=models.PositiveIntegerField(help_text='Número para ordenar visualmente (1, 2, 3...)', unique=True),
        ),
    ]
