# Generated by Django 5.2.6 on 2026-04-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0100_alter_silla_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADOPAGO', 'Mercado Pago')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago')], max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='medio_pago_restante',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago'), ('PENDIENTE', 'Pendiente')], max_length=20, null=True),
        ),
    ]
