# Generated by Django 5.2.6 on 2026-04-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0101_alter_metodopago_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoweb',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Esperando Pago'), ('PAGADO', 'Pagado - A preparar'), ('EN_PREPARACION', 'En preparación'), ('LISTO_RETIRO', 'Listo para retirar en Local'), ('EN_CAMINO', 'En camino (Moto/Correo)'), ('ENTREGADO', 'Entregado / Finalizado'), ('SOLICITA_CANCELACION', 'Cancelación Solicitada por Cliente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_PAGO', max_length=25),
        ),
    ]
