# Generated by Django 5.2.6 on 2026-04-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0102_alter_pedidoweb_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado a Proveedor'), ('COTIZADO', 'Cotizado por Proveedor'), ('CONFIRMADO', 'Confirmado por Proveedor'), ('EN_CAMINO', 'En Camino / Despachado'), ('ENTREGADO', 'Recibido en Local'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
