# Generated by Django 5.2.6 on 2026-06-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0105_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud_local', models.FloatField(default=-26.8083, help_text='Latitud de la peluquería')),
                ('longitud_local', models.FloatField(default=-54.4362, help_text='Longitud de la peluquería')),
                ('tarifa_base_envio', models.DecimalField(decimal_places=2, default=500.0, help_text='Tarifa base del envío en $', max_digits=10)),
                ('precio_por_km', models.DecimalField(decimal_places=2, default=300.0, help_text='Precio por kilómetro recorrido en $', max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración de Envíos',
                'verbose_name_plural': 'Configuración de Envíos',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('latitud_destino', models.FloatField()),
                ('longitud_destino', models.FloatField()),
                ('distancia_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='usuarios.venta')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'envios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
