# Generated by Django 5.2.6 on 2026-06-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0106_configuracionlocal_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoweb',
            name='altura_entrega',
            field=models.CharField(blank=True, default='', help_text='Altura/número de la dirección de entrega', max_length=50),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='calle_entrega',
            field=models.CharField(blank=True, default='', help_text='Calle de la dirección de entrega', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='ciudad_entrega',
            field=models.CharField(blank=True, default='', help_text='Ciudad de la dirección de entrega', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='latitud_entrega',
            field=models.FloatField(blank=True, help_text='Latitud del punto de entrega', null=True),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='longitud_entrega',
            field=models.FloatField(blank=True, help_text='Longitud del punto de entrega', null=True),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='observaciones_entrega',
            field=models.TextField(blank=True, default='', help_text='Observaciones para la entrega (color casa, referencias, etc)'),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='provincia_entrega',
            field=models.CharField(blank=True, default='', help_text='Provincia de la dirección de entrega', max_length=255),
        ),
    ]
