# Generated by Django 5.2.6 on 2026-06-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0107_pedidoweb_altura_entrega_pedidoweb_calle_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoweb',
            name='frontend_origen',
            field=models.CharField(blank=True, default='', help_text='URL del frontend donde se inició la compra', max_length=500),
        ),
    ]
