# Generated by Django 5.2.6 on 2026-06-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0108_pedidoweb_frontend_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlocal',
            name='radio_cobertura_km',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Radio máximo de cobertura de envío en km', max_digits=10),
        ),
    ]
