# Generated by Django 5.2.6 on 2026-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0109_configuracionlocal_radio_cobertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlocal',
            name='direccion_referencia',
            field=models.CharField(blank=True, default='', help_text='Referencia del local (ej. Galería X, Local Y)', max_length=255),
        ),
    ]
