# Generated by Django 5.2.6 on 2026-06-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0110_configuracionlocal_direccion_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoweb',
            name='tiempo_estimado_minutos',
            field=models.IntegerField(default=0, help_text='Tiempo estimado de entrega en minutos'),
        ),
    ]
