# Generated by Django 5.2.6 on 2026-06-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0111_pedidoweb_tiempo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='mp_payment_id_saldo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
