# Generated by Django 5.2.6 on 2026-06-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0112_turno_mp_saldo_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlocal',
            name='mp_alias',
            field=models.CharField(blank=True, default='', help_text='Alias de Mercado Pago (ej. hairsoft.mp)', max_length=50),
        ),
    ]
