# Generated by Django 5.2.6 on 2026-06-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0113_config_local_mp_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('ANULAR_VENTA', 'Anulación de Venta'), ('AJUSTE_STOCK', 'Ajuste de Stock'), ('APERTURA_CAJA', 'Apertura de Caja'), ('CIERRE_CAJA', 'Cierre de Caja'), ('INGRESO_MANUAL', 'Ingreso a Caja'), ('EGRESO_MANUAL', 'Egreso de Caja'), ('COBRO_RESTANTE', 'Cobro de Saldo Restante de Turno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='concepto',
            field=models.CharField(choices=[('TURNO_PRESENCIAL', 'Cobro de Turno Presencial'), ('TURNO_WEB', 'Cobro de Turno Web'), ('VENTA', 'Venta de Productos'), ('PEDIDO_WEB', 'Pedido Web'), ('PAGO_PROVEEDOR', 'Pago a Proveedor'), ('LIQUIDACION_SUELDO', 'Liquidación de Sueldos'), ('GASTO_OPERATIVO', 'Gasto Operativo (Yerba, etc)'), ('RETIRO_SOCIO', 'Retiro de Socio/Dueño'), ('FONDO_CAJA', 'Fondo de Caja (Sencillo)'), ('APORTE_SOCIO', 'Aporte del Dueño'), ('COBRO_DEUDA', 'Cobro de Deuda'), ('COBRO_RESTANTE', 'Cobro de Saldo Restante de Turno'), ('AJUSTE_SOBRANTE', 'Ajuste por Sobrante de Caja'), ('OTROS', 'Otros / Ajustes')], max_length=30),
        ),
    ]
