# Generated by Django 5.2.6 on 2026-06-03 23:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0114_alter_auditoria_accion_alter_movimientocaja_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTemporal',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mp_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('usado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pagos_temporales',
            },
        ),
    ]
