# Generated by Django 5.2.6 on 2026-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0115_pagotemporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True)),
                ('trabaja', models.BooleanField(default=True)),
                ('hora_apertura_manana', models.TimeField(blank=True, null=True)),
                ('hora_cierre_manana', models.TimeField(blank=True, null=True)),
                ('hora_apertura_tarde', models.TimeField(blank=True, null=True)),
                ('hora_cierre_tarde', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
                'db_table': 'horarios_atencion',
                'ordering': ['dia_semana'],
            },
        ),
    ]
