# Generated by Django 5.2.6 on 2026-06-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0117_poblar_horarios_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='dias_maximos_reserva',
            field=models.PositiveIntegerField(default=7, help_text='Máximo de días hacia adelante que un cliente puede reservar un turno'),
        ),
    ]
