# Generated by Django 5.2.6 on 2026-06-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0118_add_dias_maximos_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='rechazada',
            field=models.BooleanField(default=False),
        ),
    ]
