# Generated by Django 5.2.6 on 2026-06-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0119_cotizacion_rechazada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='rechazada',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
