# Generated by Django 5.2.6 on 2026-06-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0120_alter_cotizacion_rechazada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='dias_validez_promo_reactivacion',
            field=models.PositiveIntegerField(default=7, help_text='Días de validez del cupón de reactivación para clientes inactivos'),
        ),
    ]
