# Generated by Django 5.2.6 on 2026-07-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0121_configuracionsistema_dias_validez_promo_reactivacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='reembolso_alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias del cliente'),
        ),
        migrations.AddField(
            model_name='turno',
            name='reembolso_id_transaccion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Comprobante - Id de Transaccion'),
        ),
        migrations.AddField(
            model_name='turno',
            name='reembolso_titular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del titular'),
        ),
    ]
