# Generated by Django 5.2.6 on 2026-07-05 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0122_turno_reembolso_alias_turno_reembolso_id_transaccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='reembolso_id_transaccion',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')], verbose_name='Comprobante - Id de Transaccion'),
        ),
    ]
