# Generated by Django 5.2.6 on 2026-07-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0123_alter_turno_reembolso_id_transaccion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(condition=models.Q(('monto_seña__lte', models.F('monto_total'))), name='ck_turno_seña_no_mayor_que_total'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(condition=models.Q(('monto_total__gte', 0)), name='ck_turno_monto_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(condition=models.Q(('monto_seña__gte', 0)), name='ck_turno_monto_seña_no_negativo'),
        ),
    ]
