# Generated by Django 5.2.6 on 2026-08-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0124_turno_ck_turno_seña_no_mayor_que_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='concepto',
            field=models.CharField(choices=[('TURNO_PRESENCIAL', 'Cobro de Turno Presencial'), ('TURNO_WEB', 'Cobro de Turno Web'), ('VENTA', 'Venta de Productos'), ('PEDIDO_WEB', 'Pedido Web'), ('ANULACION_VENTA', 'Anulación de Venta'), ('PAGO_PROVEEDOR', 'Pago a Proveedor'), ('LIQUIDACION_SUELDO', 'Liquidación de Sueldos'), ('GASTO_OPERATIVO', 'Gasto Operativo (Yerba, etc)'), ('RETIRO_SOCIO', 'Retiro de Socio/Dueño'), ('FONDO_CAJA', 'Fondo de Caja (Sencillo)'), ('APORTE_SOCIO', 'Aporte del Dueño'), ('COBRO_DEUDA', 'Cobro de Deuda'), ('COBRO_RESTANTE', 'Cobro de Saldo Restante de Turno'), ('AJUSTE_SOBRANTE', 'Ajuste por Sobrante de Caja'), ('OTROS', 'Otros / Ajustes')], max_length=30),
        ),
    ]
