# Generated by Django 5.2.6 on 2026-08-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0125_alter_movimientocaja_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Imagen de Portada'),
        ),
    ]
