# Generated by Django 5.2.6 on 2026-08-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0126_configuracionsistema_imagen_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesioncaja',
            name='saldo_final_transf_real',
        ),
    ]
