# Generated by Django 5.2.6 on 2026-09-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0127_eliminar_saldo_final_transf_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='montos_rapidos_activos',
            field=models.BooleanField(default=True, help_text='Si está activo, el POS muestra los botones de montos rápidos de efectivo.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='montos_rapidos_efectivo',
            field=models.JSONField(blank=True, default=list, help_text='Lista de montos rápidos de efectivo disponibles en el POS (ej: [1000, 10000, 15000]). Lista vacía = el cajero escribe el importe manualmente.'),
        ),
    ]
