# Generated by Django 5.2.6 on 2026-09-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0128_configuracionsistema_montos_rapidos_activos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='imagen_login',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Imagen del Login'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mostrar_imagen_login',
            field=models.BooleanField(default=True, help_text='Si está activo, la pantalla de Login muestra la imagen configurada. Si no, se usa el fallback visual de marca.'),
        ),
    ]
