# Generated by Django 5.2.6 on 2026-09-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0129_configuracionsistema_imagen_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='contexto',
            field=models.JSONField(blank=True, default=dict, help_text='Contexto adicional de la operación (proceso automático, filtros, etc.)'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='endpoint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='id_operacion',
            field=models.UUIDField(blank=True, db_index=True, help_text='Identificador que agrupa todos los eventos de una misma operación (multi-modelo)', null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='mensaje',
            field=models.TextField(blank=True, default='', help_text='Mensaje o motivo de la acción'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='metodo_http',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='modulo',
            field=models.CharField(blank=True, default='', help_text='Módulo del sistema: AUTENTICACION, VENTAS, CAJA, TURNOS, ...', max_length=40),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='resultado',
            field=models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error'), ('SISTEMA', 'Sistema')], default='EXITO', max_length=10),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre y apellido del usuario en el momento de la acción', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('LOGIN_GOOGLE', 'Inicio de Sesión con Google'), ('LOGIN_FALLIDO', 'Intento de Inicio de Sesión Fallido'), ('CAMBIO_PASSWORD', 'Cambio de Contraseña'), ('ANULAR_VENTA', 'Anulación de Venta'), ('CANCELAR', 'Cancelación de Turno'), ('AJUSTE_STOCK', 'Ajuste de Stock'), ('APERTURA_CAJA', 'Apertura de Caja'), ('CIERRE_CAJA', 'Cierre de Caja'), ('INGRESO_VENTA', 'Ingreso por Venta'), ('INGRESO_TURNO', 'Ingreso por Turno'), ('INGRESO_MANUAL', 'Ingreso a Caja'), ('EGRESO_MANUAL', 'Egreso de Caja'), ('COBRO_RESTANTE', 'Cobro de Saldo Restante de Turno'), ('CONSULTAR', 'Consulta / Lectura'), ('EXPORTAR', 'Exportación de Historial')], max_length=50),
        ),
    ]
